[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[env]
NODE_ENV = "production"

# Python runtime configuration for web scraping
[phases.setup]
nixPkgs = ["python311", "pip", "nodejs_18", "chromium", "chromedriver"]

[phases.install]
cmds = [
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[phases.start]
cmd = "node server.js"
