services:
  - type: web
    name: inplay-football-scraper
    env: node
    plan: free
    buildCommand: npm install && pip3 install -r requirements.txt
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
    autoDeploy: true
